name: DarkFrame
main: net.darkdevelopers.darkbedrock.darkframe.spigot.DarkFrame
version: 1.0
authors: [LartyHD]
description: DarkFrame is a Spigot Core Plugin.
website: lars-artmann.org
#
#commands:
#    modules: